#!/bin/bash

set -euo pipefail

# certgen_path contains path to certificate generation utility certgen.sh,
# cert_root the path to the certificate tool output root directory
certgen_path=../../../certs
cert_root=${certgen_path}/gen

###############################################################################
#
# 1.  Create intermediate certificate.
#
#     Update the main branch of `./certGen.sh` with
#
#     elif [ "${1}" == "generate_intermediate_ca" ]; then
#         generate_intermediate_ca ${ROOT_CA_PASSWORD}
#
#     Certs generated by this script are not for production (e.g. they have hard-coded 
#     passwords of '1234'.  This script is only to help you understand Azure IoT Hub CA 
#     Certificates.  Use your official, secure mechanisms for this cert generation.
#     Also note that these certs will expire in 30 days.
#
###############################################################################

"${certgen_path}"/certGen.sh generate_intermediate_ca > /dev/null

echo "DPS enrollment group intermediate certificates: "
echo ""
ls -al "${cert_root}"/certs/azure-iot-test-only.intermediate*.cert.pem
ls -al "${cert_root}"/private/azure-iot-test-only.intermediate*.key.pem
