#!/bin/bash

set -euo pipefail

# certgen_path contains path to certificate generation utility certgen.sh,
# cert_root the path to the certificate tool output root directory
certgen_path=../../../certs/
cert_root=${certgen_path}/gen

###############################################################################
#
# 1.  Create root CA certificate.  The root CA certificate is used to make 
#     intermediate certificates for the DPS hierarchy.  This root certificate
#     must be replaced by a real CA certificate for production
#
#     If you already have one root CA certificate in your working folder, don't 
#     create a new one.  The new root CA certificate will overwrite the old, and 
#     any downstream certificates made from the old one will stop working.  If you 
#     want multiple root CA certificates, be sure to manage them in separate folders.
#
#     Add the following function to `./certGen.sh`:
#
#     function ca_cert_generation()
#     {
#         check_prerequisites
#         prepare_filesystem
#         generate_root_ca
#         #generate_intermediate_ca ${ROOT_CA_PASSWORD}
#     }
#
#     Update the main branch with
#
#     elif [ "${1}" == "create_root_ca_only" ]; then
#         ca_cert_generation
#
#     Certs generated by this script are not for production (e.g. they have hard-coded 
#     passwords of '1234'.  This script is only to help you understand Azure IoT Hub CA 
#     Certificates.  Use your official, secure mechanisms for this cert generation.
#     Also note that these certs will expire in 30 days.
#
###############################################################################
"${certgen_path}"/certGen.sh create_root_ca_only > /dev/null

echo "DPS root CA certificate: "
echo ""
ls -al "${cert_root}"/certs/azure-iot-test-only.root.ca.cert.pem
ls -al "${cert_root}"/private/azure-iot-test-only.root.ca.key.pem
